name: Update News Page

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  schedule:
    - cron: '0 0 * * *'    # Midnight UTC
    - cron: '0 8 * * *'    # 8:00 AM UTC
    - cron: '0 16 * * *'   # 4:00 PM UTC
  workflow_dispatch:  # Add this to enable manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas feedparser

    - name: Run the script to generate index.html
      run: |
        python news/make_news.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add news/index.html
        git commit -m "Update news/index.html via GitHub Actions" || echo "No changes to commit"
        git push
